### ISSUE TITLE
ユーザー定義辞書読み込み機能

### ISSUE THREAD

**Issue by tokuhirom** [tokuhirom/akaza#70]
今はない。skk 形式の辞書を読み込めるようにしておけば良さそう。

**Comment by tokuhirom** [comment]
設定ファイルの読み込み機能が必要。

**Comment by tokuhirom** [comment]
```
---
dicts:
  - path: /usr/share/skk/SKK-JISYO.okinawa
    encoding: euc-jp
    type: skk
```

というような感じかなぁ。
